### ISSUE TITLE
Implementation Details about training

### ISSUE THREAD

**Issue by dunbar12138** [wyysf-98/CraftsMan#10]
Thanks for your amazing work!

In the environment-setup section, you mentioned, "We train our model on 32x A800 GPUs with a batch size of 32 per GPU for 7 days."

Is this for both the shape VAE and diffusion model? If not, could you also disclose the training details of the shape VAE? e.g., how many and what type of GPUs and how many days of training.

Thank you!

**Comment by wyysf-98** [comment]
Hi, the shape VAE is trained using 8 GPU for 5 days and some reasonable results for some simple shapes in a few hours.

We found a better practice that trains a Shape VAE on a small data first and then gradually increases the number of data, which will speed up the training process.

**Comment by dunbar12138** [comment]
Thank you for your reply!!
