### ISSUE TITLE
About text-to-mesh setting.

### ISSUE THREAD

**Issue by Colezwhy** [wyysf-98/CraftsMan#11]
Hi, thank you for your awesome work!
But I wonder if the codebase now supports text-to-mesh generation?
If supports, how can I do to inference?
If not, would you please What should I do to get good text-to-mesh results?

**Comment by wyysf-98** [comment]
Hi, for the text-to-mesh generation, we first generate an image using the text prompt, then use the image-to-mesh pipeline. You can also use the MVDream to achieve text-to-mesh.

**Comment by Colezwhy** [comment]
> Hi, for the text-to-mesh generation, we first generate an image using the text prompt, then use the image-to-mesh pipeline. You can also use the MVDream to achieve text-to-mesh.

Thank you very much.
BTW, any plans for releasing the code of 2nd stage (i.e. refinement stage)? I am interested in that.

**Comment by wyysf-98** [comment]
> > Hi, for the text-to-mesh generation, we first generate an image using the text prompt, then use the image-to-mesh pipeline. You can also use the MVDream to achieve text-to-mesh.
> 
> Thank you very much. BTW, any plans for releasing the code of 2nd stage (i.e. refinement stage)? I am interested in that.

Hi, sorry that I can not provide a specific time for the release of 2nd stage. We may release a simple version of it in the next month.

**Comment by Colezwhy** [comment]
> > > Hi, for the text-to-mesh generation, we first generate an image using the text prompt, then use the image-to-mesh pipeline. You can also use the MVDream to achieve text-to-mesh.
> > 
> > 
> > Thank you very much. BTW, any plans for releasing the code of 2nd stage (i.e. refinement stage)? I am interested in that.
> 
> Hi, sorry that I can not provide a specific time for the release of 2nd stage. We may release a simple version of it in the next month.

Thanks! Looking forward to it.
