### ISSUE TITLE
Dataset Preparation

### ISSUE THREAD

**Issue by LaFeuilleMorte** [wyysf-98/CraftsMan#15]
Hi, thanks for your open-source for this brilliant work. I want to ft this model on my own datasets but I only have some 3d models (objs), Is there any scripts with which I can obtain the rendered images and point clouds and normals and occupancies. Many thanks!

**Comment by wyysf-98** [comment]
Hi, you can follow the scripts of https://github.com/autonomousvision/occupancy_networks and https://github.com/1zb/3DShape2VecSet/tree/master to get the dataset
