### ISSUE TITLE
How is the Magic Normal Brush implemented?

### ISSUE THREAD

**Issue by salanzewei** [wyysf-98/CraftsMan#2]
作者您好，感谢您新颖的工作！
请问`Magic Normal Brush`功能修改的是三维模型的二维法线图吗？若是修改了模型某一视角的法线图，如何维持模型结构拓扑的统一？是要根据新的法线图重新生成多视角图像与模型吗？

**Comment by wyysf-98** [comment]
您好，感谢对于我们工作的关注`Magic Normal Brush`功能是通过直接优化mesh的顶点坐标实现的，所以refine后的模型并不能保持原始模型的拓扑结构。
由于我们refine阶段只是单纯的增加细节，而非改变其形状，我们也可以转化为bump/displacement map，从而尽可能保留原始模型的拓扑。但是这个还需要进一步探索

**Comment by salanzewei** [comment]
感谢您的回复！我是这一领域的初学者，还有些问题向您请教下：
您所说的“通过优化mesh顶点坐标来优化模型“，是怎样实现的？是类似于mesh平滑算法、三角面片均匀化或是blender中捏拉模型这种吗？
下图中**coarse mesh===>refined mesh**这一过程，是通过生成更精细的多视角normal map，进而重新生成更精细的模型吗？
![2024-05-28 23-18-20屏幕截图](https://github.com/wyysf-98/CraftsMan/assets/74665291/94c5fa8b-47ec-4ca4-ad0f-ad5d1724df12)

**Comment by wyysf-98** [comment]
> 感谢您的回复！我是这一领域的初学者，还有些问题向您请教下： 您所说的“通过优化mesh顶点坐标来优化模型“，是怎样实现的？是类似于mesh平滑算法、三角面片均匀化或是blender中捏拉模型这种吗？ 下图中**coarse mesh===>refined mesh**这一过程，是通过局部修改各个视角下的normal map，进而重新生成更精细的模型吗？ ![2024-05-28 23-18-20屏幕截图](https://private-user-images.githubusercontent.com/74665291/334679296-94c5fa8b-47ec-4ca4-ad0f-ad5d1724df12.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTczMjA2NTMsIm5iZiI6MTcxNzMyMDM1MywicGF0aCI6Ii83NDY2NTI5MS8zMzQ2NzkyOTYtOTRjNWZhOGItNDdlYy00Y2E0LWFkMGYtYWQ1ZDE3MjRkZjEyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MDIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjAyVDA5MjU1M1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQ1ODc0NWI3NTllMWQ4YWE4MmE4MDY1NDQxMGU2YTgwYjIzYWE1ZDViYTEwYmUxY2MwZDRhMzQzNjhhODY5YWEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.gqH5RYrdtLsA1_q6aZYz0ns6b-Wu53uGfa8BNjZAW5M)

你好，我们是直接优化三角面片的顶点坐标来实现的，具体来说，我们会对表面做细分，并且对细分的三角面片更新他的坐标位置。优化的目标就是我们生成得到的多视角normal map
