### ISSUE TITLE
Multi-view generation

### ISSUE THREAD

**Issue by zhaomingheyuhan** [wyysf-98/CraftsMan#21]
Amazing work! I have some questions about your choice of multi-view generation model.
In some past works, the quality of multi view generation has a significant impact on the 3D reconstruction results. Is there a similar situation in your work as well?
Which of CRM, Wonder3D, or LGM performs better in your testing？Do you think these three models are currently the best multi-view generation models? Have you tried other models such as zero123-xl？
Thank you very much!!!

**Comment by wyysf-98** [comment]
yes, the results of mv generation will have an impact (not too much compared to other methods) on our model as it is used as the condition.  
CRM is more stable in our experiments and Wonder3D and LGM work better in some cases. I used to try Era3D and other works, which may work better but we chose CRM by default after balancing the time-consuming and the performance.  
zero123-xl is a good choice to have a try but we did not test.

**Comment by zhaomingheyuhan** [comment]
Got it! Thank you for your detailed answer!
