### ISSUE TITLE
kind inquiry about dataset split.

### ISSUE THREAD

**Issue by Moondok** [wyysf-98/CraftsMan#22]
Congrats on your great work!
Could you please provide your data split files or your dataset split strategy?
I really appreciate the help you provide, thanks in advance

**Comment by wyysf-98** [comment]
Hi, you can refer this issue for more information: https://github.com/wyysf-98/CraftsMan/issues/16

**Comment by wyysf-98** [comment]
> Sorry for the misunderstanding caused. I'm wondering how you split the origin dataset (i.e. G-Objaverse) into train, val, and test sets.

Hello, actually, we follow the 0.8:0.1:0.1 strategy after random shuffle for training, validation and testing. I think the performance is quiet easy to evaluate

**Comment by Moondok** [comment]
> > Sorry for the misunderstanding caused. I'm wondering how you split the origin dataset (i.e. G-Objaverse) into train, val, and test sets.
> 
> Hello, actually, we follow the 0.8:0.1:0.1 strategy after random shuffle for training, validation and testing. I think the performance is hard to evaluate faithfully

Got it! Thank you for the quick reply!
