### ISSUE TITLE
Problem about aligned VAE

### ISSUE THREAD

**Issue by zkaiWu** [wyysf-98/CraftsMan#23]
Thanks for your work.
And I have a question, what are the differences between  michelangelo aligned vae and michelangelo vae

**Comment by wyysf-98** [comment]
Hi, the aligned-vae is to compatibility with the original Michelangelo code: https://github.com/NeuralCarver/Michelangelo, and they use contrastive learning to align the encoded shape latent space align with the CLIP. 
We also train another shape vae without this constrain, namely w/o aligned vae

**Comment by wyysf-98** [comment]
theoretically, I think VAE without alignment may have higher bounds for reconstruction performance as it has less constrain. But the released code may have the similar performance after my evaluation
