### ISSUE TITLE
Can I generate materials and textures along with the mesh

### ISSUE THREAD

**Issue by LaFeuilleMorte** [wyysf-98/CraftsMan#3]
Thanks for your brilliant work. I tried the HF demo and I could only obtain a mesh out from an image. Can I generate the materials or textures along with the mesh.

**Comment by wyysf-98** [comment]
Hi, our current work focuses on high-quality mesh generation without paying much attention to textures. We will consider this direction in our next project. In the current state, we can use some great texture generation work to achieve this, such as:
[DreamMat](https://github.com/zzzyuqing/DreamMat?tab=readme-ov-file), [TEXTure](https://github.com/TEXTurePaper/TEXTurePaper), [SyncMVD](https://github.com/LIU-Yuxin/SyncMVD), [Fantasia3D](https://github.com/Gorilla-Lab-SCUT/Fantasia3D) etc.

**Comment by SWAPv1** [comment]
DreamMat seems the best for PBR but I'm not seeing a image reference guidance feature. That is probably all we need to generate a high quality mesh using Craftsman. Plus DM.

**Comment by wyysf-98** [comment]
> DreamMat seems the best for PBR but I'm not seeing a image reference guidance feature. That is probably all we need to generate a high quality mesh using Craftsman. Plus DM.

Indeed, we are considering injecting the image reference using IP-Adaptor in the texture synthesis Diffusion. But It may take some time to implement.
