### ISSUE TITLE
The output mesh seemed not exactly be consistent with the reference images

### ISSUE THREAD

**Issue by LaFeuilleMorte** [wyysf-98/CraftsMan#4]
Hi, thanks for your brilliant works. After a few tests on your HF demo, I found that the output mesh was not always consistent with the reference images, here are some examples:

![image2024-5-29_15-44-21](https://github.com/wyysf-98/CraftsMan/assets/43473814/45df5b63-4000-415e-8b1b-be1f6b10e6d9)

![image2024-5-29_15-44-9](https://github.com/wyysf-98/CraftsMan/assets/43473814/f8bff89c-74c5-4419-b3d9-ced4b851ea32)

The reference image has a four-leg table while the output mesh has six.

**Comment by wyysf-98** [comment]
Hi, our 3d diffusion is a generative model that takes images as reference (compared with the reconstruction model that builds the 3D mesh from sparse views), so the generated meshes are not fully aligned with the input one.

To tackle this, you can try the below methods:
1. Use the front view image of the object as input, such that you will get more accurate multi-view prediction;
2. Try another seed and mv_models, such as ImageDream prone to produce axis-aligned multi-view images;
3. We will increase the alignment between the generated mesh and the input image, by introducing more accurate condition features in future work.

**Comment by LaFeuilleMorte** [comment]
> Hi, our 3d diffusion is a generative model that takes images as reference (compared with the reconstruction model that builds the 3D mesh from sparse views), so the generated meshes are not fully aligned with the input one.
> 
> To tackle this, you can try the below methods:
> 
> 1. Use the front view image of the object as input, such that you will get more accurate multi-view prediction;
> 2. Try another seed and mv_models, such as ImageDream prone to produce axis-aligned multi-view images;
> 3. We will increase the alignment between the generated mesh and the input image, by introducing more accurate condition features in future work.

Thank you so much for the reply
