### ISSUE TITLE
About finetuning

### ISSUE THREAD

**Issue by LaFeuilleMorte** [wyysf-98/CraftsMan#5]
Hi, thanks for the brilliant work. I want to finetune on your pretrained weights. But I don't know what the dataset should look like. It would be really nice for you to provide the detained info. Thanks in advance!

**Comment by wyysf-98** [comment]
Hi, I will release some data sample in the next few days.

**Comment by wyysf-98** [comment]
Hi @LaFeuilleMorte, we already uploaded the data sample.
