### ISSUE TITLE
No module named 'apps.third_party.LGM.pipeline_mvdream'

### ISSUE THREAD

**Issue by zixian-wu** [wyysf-98/CraftsMan#6]
The following error occurs when running gradio_app.py

Traceback (most recent call last):
  File "/workspace/CraftsMan/gradio_app.py", line 62, in <module>
    from apps.third_party.LGM.pipeline_mvdream import MVDreamPipeline
ModuleNotFoundError: No module named 'apps.third_party.LGM.pipeline_mvdream'

**Comment by wyysf-98** [comment]
fixed, thanks for pointing out.
