### ISSUE TITLE
Question about Vertex Colors and Textures Output by Inference

### ISSUE THREAD

**Issue by Limbicnation** [wyysf-98/CraftsMan#7]
Hi! Great project!

Is there any information available on the vertex colors or textures output by the inference?

**Comment by flow-specter** [comment]
same question

**Comment by wyysf-98** [comment]
Hi, our current work focuses on high-quality mesh generation without paying much attention to textures. We will consider this direction in our next project. 
In the current state, we can use some great texture generation work to get the texture, such as [DreamMat](https://github.com/zzzyuqing/DreamMat?tab=readme-ov-file), [TEXTure](https://github.com/TEXTurePaper/TEXTurePaper), [SyncMVD](https://github.com/LIU-Yuxin/SyncMVD), [Fantasia3D](https://github.com/Gorilla-Lab-SCUT/Fantasia3D), etc. BUT one important thing is that they do not take a image as reference. So we may try this next few months :)

**Comment by Limbicnation** [comment]
Hi, I will look into DeamMat in the meantime. I'm also looking forward to seeing if you will implement this feature in your code. Please let me know! Thanks
